spring:
  profiles:
    active:
      - local
    group:
      local:
        - db-local
        - log-local
      dev:
        - db-dev
        - log-dev
    include:
      - db
      - log
      - jwt

server:
  port: 5001

redirect:
  url: http://localhost:3000